name: Run Go Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...

  docker:
      runs-on: ubuntu-latest
      needs: test

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: hzlq/go-ci-cd-app:latest

  deploy:
    runs-on: [self-hosted]
    needs: docker

    steps:
    - name: Deploy app
      run: |
        docker pull hzlq/go-ci-cd-app:latest
        docker stop backend || true
        docker rm backend || true
        docker run -d --name backend -p 80:80 h1zloid/go-ci-cd-app:latest

